### ISSUE TITLE
Telefish plugin compatibility issue

### ISSUE THREAD

**Issue by makiam** [ArtOfIllusion/ArtOfIllusion#213] opened 2020-09-08 20:38 UTC
Telefish plugin HeightField tool Image option incompatible with current ImagesDialog
plugin expects ImagesDialog constructor` ImagesDialog(BFrame frame, Scene scene, ImageMap image)` but actual one `ImagesDialog(WindowWidget fr, Scene sc, ImageMap selected)`

this throws NoSuchMethodError exception in log and no dialog shown

**Comment by peteihis** [comment] 2020-09-09 11:45
Oops....

I never though that plugins could use the ImagesDialog. I'm not sure any more what the reasons (real or imagined) were to change the interface/constructor but it must have seemed a logical thing to do.  I wonder what the fix should be? Change it back or add a compatibility constructor?

Of course the idea was that the parent of the dialog would always be the scene window, but thinking back there is no reason to limit it to that.

**Comment by Sailsman63** [comment] 2020-09-09 15:50
Short-term, I'll go into the repository and tag Telefish as only compatible up to 3.0

I'll take a closer look after that...

**Comment by peteihis** [comment] 2020-09-09 17:58
> tag Telefish as only compatible up to 3.0

The problem is that TeleFish is not just one plugin, it is a bundle of plugins and I believe, most of them still work. Many of them have been missing updates for a long time already, but one becoming incompatible does not affect the rest.

Basically (a bit OOT) TeleFish should have been divided into different tools or tool sets to begin with. _(And I don't think, there's anything in there that has remotely anything to do with 'tele' or 'fish', which would seem to be referring to objectives...)_

**Comment by Sailsman63** [comment] 2020-09-09 18:09
Telefish is telefish because that was the username/blog name of the person who contributed it.

They preferred maintaining a single plugin. They didn't think that keeping them separate made sense, as they were all small and simple...

I... Don't really agree with that sentiment, but changing that bit is not high on my priority list.

**Comment by Sailsman63** [comment] 2020-09-09 18:17
And looking back, the change was part of a cleanup that fixed a lot of the issues with windows stacking behind their parent, etc.

Change checked in two years ago! This probably just needs a re-compile, though.

**Comment by peteihis** [comment] 2020-09-09 18:18
> they were all small and simple...

That's why I said 'sets of tools': 6 importers, 2 editing tools, 10 camera filters.

**Comment by peteihis** [comment] 2020-09-09 18:24
> the change was part of a cleanup

Ah, it was not my doing after all. 

> This probably just needs a re-compile, though. Let's hope so :)

**Comment by Sailsman63** [comment] 2020-09-10 04:55
Quick update:

- A simple recompile is, indeed, all that we need here to get it working again.
- I want to do a more thorough review of the source files before I release that, though. The code seems to be a pastiche of several different sources, with differing licenses, and I want to make sure we're good there. This is a bigger project than it sounds because:
- There are over 200 source files! Including some bits that seem to have been copied directly from AOI source, A small CAD library, and bits of what was then the java3d api.

Apparently, this was last compiled by someone who did not believe in leaving dependencies outside of the finished .jar.

**Comment by makiam** [comment] 2020-09-10 06:08
Where are the sources for this plugin?

**Comment by Sailsman63** [comment] 2020-10-07 05:43
This should be resolved. There's a new version up in the repository.

I went back through some of my older correspondence, and Kevin Lynn had said that we was okay with someone else taking over maintenance, which is good because many of the source files do not include a license....

**Closed by Sailsman63** 2020-10-07 05:43 UTC
